name: e2e-smoke-dev

on:
  workflow_dispatch:

concurrency:
  group: e2e-dev-apothem

jobs:
  e2e-smoke-dev:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: QASE_MODE=testops xvfb-run --auto-servernum -- npm run playwright:test:e2e:smoke
        env:
          ENVIRONMENT_URL: https://dev-app-frontend-wpa8a.ondigitalocean.app
          HEADLESS_MODE: ${{ vars.HEADLESS_MODE}}
          METAMASK_SETUP_PRIVATE_KEY: ${{secrets.METAMASK_SETUP_PRIVATE_KEY}}
          METAMASK_TEST_ONE_PRIVATE_KEY: ${{secrets.METAMASK_TEST_ONE_PRIVATE_KEY}}
          METAMASK_TEST_TWO_PRIVATE_KEY: ${{secrets.METAMASK_TEST_TWO_PRIVATE_KEY}}
          METAMASK_SETUP_PASSWORD: ${{secrets.METAMASK_SETUP_PASSWORD}}
          QASE_PW_API_TOKEN: ${{secrets.QASE_PW_API_TOKEN}}
          QASE_TESTOPS_API_TOKEN: ${{secrets.QASE_TESTOPS_API_TOKEN}}
          QASE_TEST_RUN_NAME: CI Automation Tests Run - E2E Smoke
          QASE_ENVIRONMENT: dev-apothem
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report
          path: playwright-tests/test-report/
          retention-days: 30
      - uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file: playwright-tests/test-report/results.json
